---
layout: cv
title: Isaac Newtons's CV
---
# Emma Kohler
Student,.

<div id="webaddress">
<a href="emma23engel@gmail.com">emma23engel@gmail.com</a>
| <a href="http://en.wikipedia.org/wiki/Isaac_Newton">My wikipedia page</a>
</div>


## Currently

Pursuing a Bachelors Degree in Data Science at Brigham Young University of Idaho.


### Research interests

Database Engineering, Data Administration, Apperal design, Photography


## Education

`2016-2020`
__Shelley Senior High School, Shelley.__

` 2020 - 2024`
__Brigham Young University of Idaho, Rexburg__

- Associates degree

`2020 - now`
__Brigham Young University of Idaho, Rexburg__

- Working towards Bachelors 



## Awards
MCWIT - Aspirations in computing Award

### Experience

`May 2024 - July 2024  `
__BYU Employment ~ Provo, UT: Church Youth Camp Counselor (seasonal position)__
-Taught groups of youth, individually and with a Co-counselor. 

-Promoted and maintained an uplifting environment aligned with a focus on helping participants grow socially, intellectually, and spiritually. 

`July 2024 - December 2024`
__Great Harvest ~ Idaho Falls, ID: Baker/Server/Prepper (seasonal position)__
-Prepped food and drink orders. 

-Oversaw cash and credit interactions.

-prepared and baked the product.

`August 2023 - October 2023`
__CinnaBear Bakery ~ Gardiner, MT: Server/Prepper (seasonal position)__
-Prepped food and drink orders. 

-Oversaw cash and credit interactions. 

`July 2021 - December 2022`
__The Church of Jesus Christ of Latter-day Saints ~ Fort Worth, TX: Volunteer Representative__  
-Trained new, incoming volunteers in the type of work done.  

-Participated in leadership roles. 

-Planned and carried out lessons for groups ranging from very large to individual basis. 

`May 2020 - August 2020`
__Snogo Shaved Ice ~ Shelley, ID: Server/Prepper (seasonal position)__
-Offered a promotion to manager after my first summer of working here. 

-Managed workplace individually during shifts and oversaw cash and credit interactions. 

`May 2019 - August 2019`
__Apple Athletic Club ~ Idaho Falls, ID — Summer Day Camp Counselor (seasonal position)__
-Planned, organized, and facilitated camp activities for 50 kids for an entire week. 

-Worked flexibly with co-workers to meet the needs of campers, parents, and gym members. 

-Helped participants enjoy activities while ensuring adherence to protocol. 

## Occupation

__Student__, Rexburg


<!-- ### Footer

Last updated: May 2013 -->